# Generated by Django 2.2.9 on 2019-12-19 21:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Título')),
                ('navigation', wagtail.core.fields.StreamField([('page_link', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(label='Texto item menú', max_length=255, required=False)), ('page', wagtail.core.blocks.PageChooserBlock(label='Página')), ('sub_links', wagtail.core.blocks.StreamBlock([('page_link', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(label='Texto item menú', max_length=255, required=False)), ('page', wagtail.core.blocks.PageChooserBlock(label='Página'))])), ('external_link', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(label='Texto item menú', max_length=255, required=False)), ('link', wagtail.core.blocks.CharBlock(label='URL', required=False))])), ('document_link', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(label='Texto item menú', max_length=255, required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(label='Documento'))]))], label='Sub menú', required=False)), ('open_page_new_window', wagtail.core.blocks.BooleanBlock(default=False, help_text='Seleccione si desea abrir en una nueva pestaña cuando el usuario de clic', label='Abrir en una nueva página', required=False))])), ('external_link', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(label='Texto item menú', max_length=255, required=False)), ('link', wagtail.core.blocks.CharBlock(label='URL', required=False)), ('sub_links', wagtail.core.blocks.StreamBlock([('page_link', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(label='Texto item menú', max_length=255, required=False)), ('page', wagtail.core.blocks.PageChooserBlock(label='Página'))])), ('external_link', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(label='Texto item menú', max_length=255, required=False)), ('link', wagtail.core.blocks.CharBlock(label='URL', required=False))])), ('document_link', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(label='Texto item menú', max_length=255, required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(label='Documento'))]))], label='Sub menú', required=False))])), ('document_link', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(label='Texto item menú', max_length=255, required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(label='Documento')), ('sub_links', wagtail.core.blocks.StreamBlock([('page_link', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(label='Texto item menú', max_length=255, required=False)), ('page', wagtail.core.blocks.PageChooserBlock(label='Página'))])), ('external_link', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(label='Texto item menú', max_length=255, required=False)), ('link', wagtail.core.blocks.CharBlock(label='URL', required=False))])), ('document_link', wagtail.core.blocks.StructBlock([('display_text', wagtail.core.blocks.CharBlock(label='Texto item menú', max_length=255, required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(label='Documento'))]))], label='Sub menú', required=False))]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Menú de Navegación',
                'verbose_name_plural': 'Menús de Navegación',
            },
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Página principal'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.MenuPage'),
        ),
    ]
