# Generated by Django 2.2.9 on 2019-12-19 23:35

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0005_auto_20191219_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('mainblock', wagtail.core.blocks.StructBlock([('bg_imagen', wagtail.images.blocks.ImageChooserBlock(help_text='Seleccione una imagen para el fondo de la seccion de bienvenida. Se recomienda imagen de 1910x1055', label='Imagen de fondo de seccion', required=True)), ('message_welcome', wagtail.core.blocks.CharBlock(label='Mensaje de Bienvenida: ')), ('sub_title', wagtail.core.blocks.CharBlock(help_text='Para efectos de la animacion se debe separar por comas. Ejemplo: CEO DevFolio,Web Developer,Web Designer,Frontend Developer,Graphic Designer', label='Subtitulo de Mensaje de Bienvenida: '))]))], blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CongGeneralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_menu', models.CharField(max_length=15, verbose_name='Ingrese Texto de menu')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Configuraciones Generales',
            },
        ),
    ]
