# Generated by Django 2.2.9 on 2019-12-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191220_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='conggeneralsettings',
            name='text_copyright',
            field=models.CharField(max_length=255, null=True, verbose_name='Ingrese Texto pie de pagina: Copyright'),
        ),
    ]
