# Generated by Django 2.2.9 on 2019-12-27 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_book_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.Book'),
        ),
    ]
