# Generated by Django 2.2.9 on 2019-12-27 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_book_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Portafolio', 'verbose_name_plural': 'Portafolios'},
        ),
    ]
