# Generated by Django 2.2.9 on 2019-12-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20191227_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='book',
        ),
    ]
