# Generated by Django 2.2.9 on 2019-12-30 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_delete_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
